
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

namespace Sanatana.DataGenerator.EntityFrameworkCore.Internals
{
    public class EfCoreModelService
    {
        private readonly Func<DbContext> _dbContextFactory;


        //init
        public EfCoreModelService(Func<DbContext> dbContextFactory)
        {
            _dbContextFactory = dbContextFactory ?? throw new ArgumentNullException(nameof(dbContextFactory));
        }


        //methods
        public virtual Type[] GetConfiguredEntities()
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                IEnumerable<IEntityType> efEntityTypes = dbContext.Model.GetEntityTypes();
                return efEntityTypes.Select(x => x.ClrType).ToArray();
            }
        }

        public virtual bool CheckHasAutoGeneratedProperties(Type typeToCheck)
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                string entityName = TypeExtensions.DisplayName(typeToCheck);
                IEntityType efEntityType = dbContext.Model.FindEntityType(entityName);

                IEnumerable<IProperty> keyProperties = efEntityType.GetProperties();
                keyProperties = keyProperties.Where(x => x.ValueGenerated != ValueGenerated.OnAdd 
                    || x.ValueGenerated == ValueGenerated.OnAddOrUpdate);
                return keyProperties.Any();
            }
        }

        public virtual PropertyInfo[] GetPrimaryKeysManuallyGenerated(Type typeToCheck)
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                string entityName = TypeExtensions.DisplayName(typeToCheck);
                IEntityType efEntityType = dbContext.Model.FindEntityType(entityName);

                IEnumerable<IKey> keys = efEntityType.GetKeys();
                IEnumerable<IProperty> keyProperties = keys.SelectMany(x => x.Properties);
                keyProperties = keyProperties.Where(x => x.ValueGenerated == ValueGenerated.Never); //skip auto generated keys
                return keyProperties.Select(x => x.PropertyInfo).ToArray();
            }
        }

        public virtual Type[] GetParentEntities(Type typeToCheck)
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                string entityName = TypeExtensions.DisplayName(typeToCheck);
                IEntityType efEntityType = dbContext.Model.FindEntityType(entityName);
                IForeignKey[] foreignKeys = efEntityType.GetForeignKeys().ToArray();
                return foreignKeys
                    .Select(x => x.PrincipalEntityType.ClrType)
                    .ToArray();
            }
        }

        public virtual void SetForeignKeysOnChild(object childInstance, object parentInstance)
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                Type childType = childInstance.GetType();
                Type parentType = parentInstance.GetType();

                string entityName = TypeExtensions.DisplayName(childType);
                IEntityType efEntityType = dbContext.Model.FindEntityType(entityName);

                IEnumerable<IForeignKey> foreignKeys = efEntityType.GetForeignKeys();
                IForeignKey[] foreignKeysToParent = foreignKeys
                    .Where(x => x.PrincipalEntityType.ClrType == parentType)
                    .ToArray();

                foreach (IForeignKey foreignKey in foreignKeysToParent)
                {
                    for (int i = 0; i < foreignKey.PrincipalKey.Properties.Count; i++)
                    {
                        PropertyInfo parentProp = foreignKey.PrincipalKey.Properties[i].PropertyInfo;
                        object foreignKeyValue = parentProp.GetValue(parentInstance);

                        PropertyInfo childProp = foreignKey.Properties[i].PropertyInfo;
                        childProp.SetValue(childInstance, foreignKeyValue);
                    }
                }
            }
            
        }
    }
}
