using Sanatana.DataGenerator.Storages;
using Sanatana.EntityFramework.Batch.Commands.Merge;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Sanatana.EntityFramework.Batch.ColumnMapping;
using System.Linq.Expressions;

namespace Sanatana.DataGenerator.EntityFramework
{
    public class EntityFrameworkPersistentStorage : EntityFrameworkRequestCapacityProvider, 
        IPersistentStorage, IPersistentStorageSelector
    {
        //init
        public EntityFrameworkPersistentStorage(Func<DbContext> dbContextFactory)
            : base(dbContextFactory)
        {
        }

        public virtual void Setup()
        {
        }


        //IDisposable
        public virtual void Dispose()
        {
        }

        //IPersistentStorage methods
        public virtual async Task Insert<TEntity>(List<TEntity> entities)
            where TEntity : class
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                var merge = new MergeCommand<TEntity>(dbContext, entities);

                //will set ids generated by database on entity instances
                merge.Output.SetExcludeAllByDefault(true)
                    .SetExcludeDbGeneratedByDefault(ExcludeOptions.Include)
                    ;

                int insertedCount = await merge.ExecuteAsync(MergeType.Insert)
                    .ConfigureAwait(false);
            }
        }


        //IPersistentStorageSelector methods
        public virtual List<TEntity> Select<TEntity, TOrderByKey>(Expression<Func<TEntity, bool>> filter,
            Expression<Func<TEntity, TOrderByKey>> orderBy, bool isAsc, int skip, int take)
            where TEntity : class
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                IQueryable<TEntity> query = dbContext.Set<TEntity>()
                    .Where(filter);

                if(orderBy != null)
                {
                    query = isAsc
                        ? query.OrderBy(orderBy)
                        : query.OrderByDescending(orderBy);
                }

                List<TEntity> entities = query
                    .Skip(skip)
                    .Take(take)
                    .ToList();
                return entities;
            }
        }

        public virtual long Count<TEntity>(Expression<Func<TEntity, bool>> filter)
            where TEntity : class
        {
            using (DbContext dbContext = _dbContextFactory())
            {
                long count = dbContext.Set<TEntity>()
                    .Where(filter)
                    .LongCount();
                return count;
            }
        }

    }
}
